name: Build ML base image

on:
  push:
    branches:
      - "AugUpgrade"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.7
        with:
          image: ivukotic/ml_base
          tags: aug_upgrade, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
